arm64: config: Disable FSL_EDMA config
GVS builds are failing due to enabling FSL_EDMA which is
enabled from upstream. Fixing build errors are not feasible as
spinlock API used in several places in the files fsl-edma.c and
fsl-edma-common.c

Build error snippet

847807:                  from
/dvs/git/dirty/git-master_modular/kernel/kernel-5.10/drivers/dma/fsl-edma.c:12:
847808:
/dvs/git/dirty/git-master_modular/kernel/kernel-5.10/include/linux/spinlock.h:327:67:
note: expected â€˜spinlock_t *â€™ {aka â€˜struct spinlock *â€™} but
argument is of type â€˜raw_spinlock_t *â€™ {aka â€˜struct raw_spinlock
*â€™}
847809:   327 | static __always_inline raw_spinlock_t
*spinlock_check(spinlock_t *lock)
847810:       |
~~~~~~~~~~~~^~~~
847811:
/dvs/git/dirty/git-master_modular/kernel/kernel-5.10/drivers/dma/fsl-edma.c:452:26:
error: passing argument 1 of â€˜spin_unlock_irqrestoreâ€™ from
incompatible pointer type [-Werror=incompatible-pointer-types]
847812:   452 |   spin_unlock_irqrestore(&fsl_chan->vchan.lock, flags);
847813:       |                          ^~~~~~~~~~~~~~~~~~~~~
847814:       |                          |
847815:       |                          raw_spinlock_t * {aka struct
raw_spinlock *}

Bug 4111307

Signed-off-by: Rajesh Gumasta <rgumasta@nvidia.com>
Change-Id: I979daeecdbc1c3b5d221193e2430c9d8d92c29bd
Reviewed-on: https://git-master.nvidia.com/r/c/linux-5.10/+/2740003
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>