gpu: nvgpu: fix uninitialized variable error
Enabling Kcov and KASAN causes below compilation failure :
common/mm/vm_area.c:255:3: error: ‘vma’ may be used uninitialized in this
function [-Werror=maybe-uninitialized]

Fix this by correcting failure cases in function nvgpu_vm_area_alloc()

Bug 2155608

Change-Id: Id4070157f2a8bd7043b0c49effb6f61cce5eecc2
Signed-off-by: Deepak Nibade <dnibade@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/c/linux-nvgpu/+/2359496
Reviewed-by: automaticguardword <automaticguardword@nvidia.com>
Reviewed-by: svc-mobile-coverity <svc-mobile-coverity@nvidia.com>
Reviewed-by: svc-mobile-misra <svc-mobile-misra@nvidia.com>
Reviewed-by: svc-mobile-cert <svc-mobile-cert@nvidia.com>
Reviewed-by: Alex Waterman <alexw@nvidia.com>
Reviewed-by: Debarshi Dutta <ddutta@nvidia.com>
Reviewed-by: Konsta Holtta <kholtta@nvidia.com>
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>
GVS: Gerrit_Virtual_Submit
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>