firmware: tegra: Fix redefinition error
[failed defconfig combination]
    CONFIG_NV_TEGRA_BPMP=n
    CONFIG_DEBUG_FS=y

When building a kernel with the config setting above, errors occur:
    drivers/soc/tegra/fuse/fuse-burn.o:
        In function `tegra_bpmp_debugfs_add_file':
    include/soc/tegra/tegra_bpmp.h:72:
        multiple definition of `tegra_bpmp_debugfs_add_file'
    include/soc/tegra/tegra_bpmp.h:72:
        first defined here

So this patch fixes it by adding "static inline" to the header.
Also, it adds similar inline function for the following case:
    CONFIG_NV_TEGRA_BPMP=y
    CONFIG_DEBUG_FS=n

Bug 200591811
Bug 200663781

Change-Id: If90cbf9fc82d340597248251e79a78cbb0bb7b7e
Signed-off-by: Nicolin Chen <nicolinc@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/c/linux-nvidia/+/2442857
Reviewed-by: automaticguardword <automaticguardword@nvidia.com>
Reviewed-by: Bitan Biswas <bbiswas@nvidia.com>
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>
GVS: Gerrit_Virtual_Submit