nvidia: crypto: changes to fix compilation error
fix below compilaiton error when enabling CONFIG_COMPAT flag in K5.10
/home/mbhardwaj/59/kernel/nvidia/drivers/crypto/tegra-cryptodev.c: In function ‘tegra_crypto_dev_ioctl’:
/home/mbhardwaj/59/kernel/nvidia/drivers/crypto/tegra-cryptodev.c:1632:16: error: this statement may fall through [-Werror=implicit-fallthrough=]
   rng_req.type = rng_req_32.type;
   ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/home/mbhardwaj/59/kernel/nvidia/drivers/crypto/tegra-cryptodev.c:1636:2: note: here
  case TEGRA_CRYPTO_IOCTL_SET_SEED:
  ^~~~
/home/mbhardwaj/59/kernel/nvidia/drivers/crypto/tegra-cryptodev.c:1694:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
   rng_req.rdata = (u8 __user *)(void *)(__u64)rng_req_32.rdata;
   ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mbhardwaj/59/kernel/nvidia/drivers/crypto/tegra-cryptodev.c:1698:2: note: here
  case TEGRA_CRYPTO_IOCTL_GET_RANDOM:

Signed-off-by: Manish Bhardwaj <mbhardwaj@nvidia.com>
Change-Id: I070c568ed8a8bd12014468b27a1ccf8ecf63d0d9
Reviewed-on: https://git-master.nvidia.com/r/c/linux-nvidia/+/2456804
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>
Reviewed-by: Bitan Biswas <bbiswas@nvidia.com>
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>