fs: export functions vfs_read() and vfs_write()
Following build errors are seen while enabling CONFIG_TEGRA_ADSP_FILEIO.

  ERROR: modpost: "vfs_read" [drivers/platform/tegra/nvadsp/nvadsp.ko]
    undefined!
  ERROR: modpost: "vfs_write" [drivers/platform/tegra/nvadsp/nvadsp.ko]
    undefined!

Thus export vfs_read() and vfs_write() functions to fix above. This was
present in v4.14, but later removed in upstream kernel as there were no
module users.

Bug 200593718
Bug 200657500

Change-Id: I77053e3d99e890b88d0a246be75e49bfd4c06608
Signed-off-by: Sameer Pujar <spujar@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/c/linux-5.9/+/2412301
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>