fs: ext4: fix gcc 7.3 build
Fix below build error for l4t with gcc 7.3:
/home/bbiswas/wrkspace/br_l4t-dev-k-4.9_1/kernel/kernel-4.14/fs/ext4/readpage.c: In function ‘ext4_mpage_readpages▒
▒:
/home/bbiswas/wrkspace/br_l4t-dev-k-4.9_1/kernel/kernel-4.14/fs/ext4/readpage.c:159:2: error: ‘memset’ used with l
ength equal to number of elements without multiplication by element size [-Werror=memset-elt-size]
  memset(blocks, 0x0, MAX_BUF_PER_PAGE);
  ^~~~~~
cc1: all warnings being treated as errors

Change-Id: I1ba6791a812dc94478b2eb16c5f402cd36444925
Signed-off-by: Bitan Biswas <bbiswas@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/1782638
(cherry picked from commit 202d2ecaf11111201ef8b780d70f5a347159663d)
Reviewed-on: https://git-master.nvidia.com/r/c/linux-5.9/+/2423108
Reviewed-by: automaticguardword <automaticguardword@nvidia.com>
Reviewed-by: Sachin Nikam <snikam@nvidia.com>
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>
GVS: Gerrit_Virtual_Submit
Tested-by: Sachin Nikam <snikam@nvidia.com>
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>