clk: tegra: T210b01 clock data
Introduce T210b01 PLL static data in a separate file. Also split out
PLL init table data from the common init table data and make an
updated version for T210b01.

Add the new 60MHz output for the UTMIPLL which can be used as a PLL_RE
reference.

Add UPHY branch of PLL_P.

Based on work by Alex Frid <afrid@nvidia.com>

Bug 1867980

Change-Id: I0ff719d265cb08f9ccd45e51231ac81f99d05bee
Signed-off-by: Peter De Schrijver <pdeschrijver@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/1576318
(cherry picked from commit 596d676fa5c357229bc4884f15a175efec28a39f)
[nicolinc: aligned with K4.14 code line since some previous changes
 are not required to get merged any more; Fixed checkpatch errors:
   WARNING: void function return statements are not generally useful
   #1233: FILE: drivers/clk/tegra/clk-tegra210b01.c:862:
   +	return;
   +}
   ERROR: space required after that ',' (ctx:VxV)
   #2539: FILE: drivers/clk/tegra/clk-tegra210b01.c:2168:
   +	reg &= ~GENMASK(20,0);
 Also squashed the commit b66b091a788f ("clk: tegra: remove unused
 code") as it just removed two functions that were added here.]
Signed-off-by: Nicolin Chen <nicolinc@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/1772000
(cherry picked from commit 49d465519f5498d304d856731babc2e789031503)
[nicolinc: dropped clk-tegra210b01 part as it's moved to nvidia repo]
Signed-off-by: Nicolin Chen <nicolinc@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/c/linux-5.9/+/2427565
Reviewed-by: automaticguardword <automaticguardword@nvidia.com>
Reviewed-by: Sachin Nikam <snikam@nvidia.com>
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>
GVS: Gerrit_Virtual_Submit
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>