nvadsp: fix build errors on v5.9
Following build errors are seen when ADSP configs CONFIG_TEGRA_ADSP_FILEIO
and CONFIG_TEGRA_ADSP_LPTHREAD are enabled.

* Error due to "segment.h"

  adsp_lpthread.c:14:10: fatal error: asm/segment.h: No such file or
    directory
  adspff.c:17:10: fatal error: asm/segment.h: No such file or directory

  (asm/segment.h inclusion is removed as asm/uaccess.h already takes care
   of required dependencies)

* Error due to unavailable structure "sched_param"

  adspff.c:517:21: error: variable ‘param’ has initializer but incomplete
    type
  adspff.c:518:3: error: ‘const struct sched_param’ has no member named
    ‘sched_priority’

  (Replace <linux/sched/types.h> with <uapi/linux/sched/types.h> to fix
   this build issue)

* Error due to unavailable "get_ds()"

  adspff.c:63:9: error: implicit declaration of function ‘get_ds’; did you
    mean ‘get_fs’? [-Werror=implicit-function-declaration]

  (Fixed by replacing get_ds() with KERNEL_DS. The get_ds() support is
   removed from upstream kernel)

Bug 200593718
Bug 200657500

Change-Id: I8b9cbed5ee42f34cf3731ea2d2f06aa760c28358
Signed-off-by: Sameer Pujar <spujar@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/c/linux-nvidia/+/2412299
Reviewed-by: automaticguardword <automaticguardword@nvidia.com>
Reviewed-by: Mohan Kumar D <mkumard@nvidia.com>
Reviewed-by: Dipesh Gandhi <dipeshg@nvidia.com>
Reviewed-by: Sharad Gupta <sharadg@nvidia.com>
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>
GVS: Gerrit_Virtual_Submit