drm/tegra: Fix build for Linux-v5.16-rc1
Building the Tegra DRM out-of-tree module against the current upstream
mainline kernel is failing and errors such as the following are seen.

ERROR: modpost: module tegra-drm-next uses symbol dma_buf_detach from
	namespace DMA_BUF, but does not import it.
ERROR: modpost: module tegra-drm-next uses symbol dma_buf_vunmap from
	namespace DMA_BUF, but does not import it.
ERROR: modpost: module tegra-drm-next uses symbol dma_buf_put from
	namespace DMA_BUF, but does not import it.

Following upstream commit 16b0314aa746 ("dma-buf: move dma-buf symbols
into the DMA_BUF module namespace"), it is now necessary to import the
DMA_BUF module namespace into the Tegra DRM driver to fix this.

Change-Id: I9dbd0e3c97b3ccf09982fdb72ef8a9a715d873de
Signed-off-by: Jon Hunter <jonathanh@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/c/linux-nvidia/+/2621643
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>
Reviewed-by: svc_kernel_abi <svc_kernel_abi@nvidia.com>
Reviewed-by: Mikko Perttunen <mperttunen@nvidia.com>
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>
GVS: Gerrit_Virtual_Submit