arm64: tegra: fix circular dependency with PCI_MSI
We currently have a circular dependency with PCI_MSI that is detected
with Linux 4.19 build system:

error: recursive dependency detected!
 symbol PCI_MSI_IRQ_DOMAIN depends on PCI_MSI
 symbol PCI_MSI is selected by PCI_TEGRA
 symbol PCI_TEGRA depends on PCI_MSI_IRQ_DOMAIN

Fix the dependency by removing explicit select statement from
ARCH_TEGRA_18x_SOC configuration. PCI_MSI will be implicitly selected
anyway whenever PCI_TEGRA is selected.

Change-Id: I72240db76333bf3369580f06703e6346c4c2b0b4
Signed-off-by: Timo Alho <talho@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/1918521
Reviewed-by: Manikanta Maddireddy <mmaddireddy@nvidia.com>
GVS: Gerrit_Virtual_Submit
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>