video: tegra: dc: hdcp: fix build errors on v5.9
* Error due to unavailable "get_ds()"

nvhdcp_hdcp22_methods.c:508:9: error: implicit declaration of function
"get_ds"; did you mean "get_fs"?

(Fixed by replacing get_ds() with KERNEL_DS. The get_ds() support is
removed from upstream kernel)

* Error due to variable length array 'buf'

error: ISO C90 forbids variable length array 'buf'

(hdcp driver contains VLA. Until this is eliminated, turn off VLA
warnings [-Wno-vla])

* Error due to deprecated 32-bit ktime and timespec APIs

hdmihdcp.c:1123:15: error: implicit declaration of function
'timespec_to_ns'; did you mean 'timespec64_to_ns'?
hdmihdcp.c:1122:2: error: implicit declaration of function
'ktime_get_ts'; did you mean 'ktime_get_ns'?

(Fixed by using 64-bit ktime and timespec APIs)

* Error due to deprecated i2c_release_client

hdmihdcp.c:2554:2: error: implicit declaration of function
'i2c_release_client'; did you mean 'i2c_verify_client

(Fixed by using i2c_unregister_device)

Bug 200515779

Change-Id: I81bda424453d4484c844b3ad3117a05af8b6bac7
Signed-off-by: Ahung Cheng <ahcheng@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/c/linux-nvidia/+/2466774
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>