arm64: configs: tegra: Enable CONFIG_TEGRA_SOCTHERM
There is a compiling error on T210 as the soctherm driver is not
compiled at all with tegra_defconfig:
  ERROR: "tegra_soctherm_gpu_tsens_invalidate"
  [drivers/gpu/nvgpu/nvgpu.ko] undefined!

So this patch enables CONFIG_TEGRA_SOCTHERM in the tegra_defconfig
to fix it.

CONFIG_TEGRA_SOCTHERM=y

Bug 200340638

Change-Id: Ida5b4e1c623a7fea7b74f018388faedf5ab3f079
Signed-off-by: Nicolin Chen <nicolinc@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/1553102
(cherry picked from commit c6c78ae15777fd92c29c4fe713bf6c72be107f5b)
[nicolinc: updated commit message as there's no more downstream powergate
 driver, however, there's still the same build error happening to nvgpu]
Signed-off-by: Nicolin Chen <nicolinc@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/1776473
(cherry picked from commit e0e9f6a9b5c7f1a8e0f5f0c317dbf80a6d4f2704)
Reviewed-on: https://git-master.nvidia.com/r/c/linux-5.9/+/2443901
Tested-by: Sagar Kamble <skamble@nvidia.com>
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>
Reviewed-by: Sagar Kamble <skamble@nvidia.com>
Reviewed-by: automaticguardword <automaticguardword@nvidia.com>
Reviewed-by: Sachin Nikam <snikam@nvidia.com>
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>
GVS: Gerrit_Virtual_Submit