gpu: nvgpu: global_ctx: fix misra rule 1.1 error
Fix typedef of global_ctx_mem_destroy_fn function pointer

Error: MISRA C-2012 Rule 1.1:
nvgpu/drivers/gpu/nvgpu/include/nvgpu/gr/global_ctx.h:35:
misra_violation: typedef name has already been declared (with same type)

NVGPU-3224

Change-Id: Ic54d40f6d308ce407973c49602fbb86264776f44
Signed-off-by: Nitin Kumbhar <nkumbhar@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/2112704
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>