tegra-firwmares: read AIDR dynamically
The field cpuinfo->reg_aidr was added to support Denvers... it is
non-standard field that will not exist in future kernels without
NVIDIA patches

Let's read this register when requested.

Also, fix the following build error:
error: ISO C90 forbids variable length array ‘reader_string’ [-Werror=vla]
  char reader_string[TFW_VERSION_MAX_SIZE];
  ^~~~
cc1: all warnings being treated as errors

Bug 200593718

Change-Id: I366a395ac987e8dcd0819f7743fc015bcc78ec1c
Signed-off-by: dmitry pervushin <dpervushin@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/c/linux-nvidia/+/2335451
Reviewed-by: automaticguardword <automaticguardword@nvidia.com>
Reviewed-by: Bitan Biswas <bbiswas@nvidia.com>
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>
GVS: Gerrit_Virtual_Submit
Tested-by: Sameer Pujar <spujar@nvidia.com>
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>