video: tegra: nvmap: Move vpr symbols to tegra_vpr
Making nvmap as LKM is leading to following failures:
- undefined reference to `tegra_vpr_resize'
- undefined reference to `tegra_vpr_size'
- undefined reference to `tegra_vpr_start'
These variables are defined in nvmap and being referenced by tegra_vpr.
tegra_vpr, nvmap are builtin modules in 5.10 kernel. If nvmap is made
LKM then it will be compiled during make modules phase. Hence tegra_vpr
compilation lead to undefined reference errors.
In order to resolve this issue, define these symbols in tegra_vpr and
export them so that nvmap can use it.

Bug 200722684

Change-Id: I8d249a24d7cbf95e8a2eb932f7998ddbb8f3fdcb
Signed-off-by: Ketan Patil <ketanp@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/c/linux-nvidia/+/2675880
Reviewed-by: svc_kernel_abi <svc_kernel_abi@nvidia.com>
Reviewed-by: Ashish Mhetre <amhetre@nvidia.com>
Reviewed-by: Sachin Nikam <snikam@nvidia.com>
GVS: Gerrit_Virtual_Submit