drivers: pva: fix Cert_c defect
Error: Passing unterminated string symID->symbol_name to strcmp,
which expects a null-terminated string. Fix the defect by null
terminating the string before sue.

CID 512400

Bug 3512545

Change-Id: I71836a062725b49e5e5c90824e572cbe048df3d4
Signed-off-by: Prateek Patel <prpatel@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/c/linux-nvidia/+/2696221
Reviewed-by: svcacv <svcacv@nvidia.com>
Reviewed-by: svc_kernel_abi <svc_kernel_abi@nvidia.com>
Reviewed-by: svc-mobile-coverity <svc-mobile-coverity@nvidia.com>
Reviewed-by: svc-mobile-cert <svc-mobile-cert@nvidia.com>
Reviewed-by: Sachin Nikam <snikam@nvidia.com>
GVS: Gerrit_Virtual_Submit