video: tegra: nvmap: Fix build for Linux-v5.16-rc1
Building the NVMAP out-of-tree module against the current upstream
mainline kernel is failing and errors such as the following are seen.

ERROR: modpost: module nvmap uses symbol dma_buf_put from namespace
	DMA_BUF, but does not import it.
ERROR: modpost: module nvmap uses symbol dma_buf_get from namespace
	DMA_BUF, but does not import it.
ERROR: modpost: module nvmap uses symbol dma_buf_export from namespace
	DMA_BUF, but does not import it.

Following upstream commit 16b0314aa746 ("dma-buf: move dma-buf symbols
into the DMA_BUF module namespace"), it is now necessary to import the
DMA_BUF module namespace into the Tegra DRM driver to fix this.

The following build issue is also observed with the current mainline
kernel and so fix this by ensuring the appropriate header file is
included for NVMAP.

nvmap/nvmap_dev.c:1408:21: error: implicit declaration of function
 	‘sched_clock’ [-Werror=implicit-function-declaration]
 ulong start_time = sched_clock();
                       ^~~~~~~~~~~

Change-Id: Idade0a549e5aba6572357684e813f656cea346bc
Signed-off-by: Jon Hunter <jonathanh@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/c/linux-nvidia/+/2621642
Reviewed-by: svc_kernel_abi <svc_kernel_abi@nvidia.com>
Reviewed-by: Ketan Patil <ketanp@nvidia.com>
Reviewed-by: Sachin Nikam <snikam@nvidia.com>
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>
GVS: Gerrit_Virtual_Submit