drivers: wireless: fix Coverity defect
error: The or condition "status != HALMAC_CMD_PROCESS_DONE ||
status != HALMAC_CMD_PROCESS_ERROR" will always be true because status
cannot be equal to two different values at the same time, so it must be
not equal to at least one of them. Fix the defect by separating the
two err conditions.

CID 10127896

Bug 3461002

Change-Id: If5710f48714e5c824357e2fb19e611a1080939f6
Signed-off-by: Prateek Patel <prpatel@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/c/linux-nvidia/+/2659178
Reviewed-by: svc-mobile-coverity <svc-mobile-coverity@nvidia.com>
Reviewed-by: svc-mobile-cert <svc-mobile-cert@nvidia.com>
Reviewed-by: svc_kernel_abi <svc_kernel_abi@nvidia.com>
Reviewed-by: Sachin Nikam <snikam@nvidia.com>
GVS: Gerrit_Virtual_Submit